// Generated by LiveScript 1.6.0
(function(){
  var remotemon, ref$, z, readJson, readYaml;
  remotemon = require('../dist/main');
  ref$ = require('../dist/common'), z = ref$.z, readJson = ref$.readJson, readYaml = ref$.readYaml;
  remotemon("./test/opts.yaml");
}).call(this);
