global:
  file: us
  proj:
    etc: service
    name:
      - utils
      - next
  sshport: 45
  first:
    - verbose
  second: recursive
  files:
    - test/opt.yaml
    - null
    - hungryhippo
remotehost: pi@192.168.43.142
ssh: -t -o LogLevel=QUIET -p {{global.sshport}}
remotefold: ~/test3
defarg:
  - pi@192.168.43.50
  - package.json
  - -tt
ignore:
  - /mnt/c/code/remotemon/.remotemon.yaml
longname:
  verbose: 0
  defarg:
    - foo
    - bar
    - paper
  ssh: -tt -o LogLevel=QUIET -p 45
  local:
    - echo 'hello world 11'
ytv:
  defarg: 1
  watch: false
  local:
    - youtube-dl -f 18 {{0}}
echo:
  verbose: 1
  local:
    - echo 'from locale'
  remote:
    - echo 'from remote'
dry:
  verbose: 1
  defarg:
    - 1
    - 2
  local:
    - node {{0}}
bar:
  defarg:
    - --version
    - .inf
  local:
    - node {{0}} {{1}}
  rsync: true
  remote:
    - echo 'hello world'
  final:
    - echo 'hello world'

local:
  - echo "hello world"

