global:
  file: dist/main.js
  proj: utils
  sshport: 45
  first: &first
    - verbose
  second: &second
    - recursive
  files: &files
    - test/opt.yaml
    - null
    - hungryhippo

# remotehost: pi@192.168.43.50

defargs: [pi@192.168.43.50,package.json,-tt]

# remotehost: 'hello world {{0}}'

remotehost: pi@192.168.43.50

remotefold: ~/test3

watch:
  # - .editorconfig
  - .remotemon.yaml

# chokidar:
#   ignored:
#     - ./remotemon.yaml

# verbose: 0

# ssh: -tt -o 'RequestTTY no' -p 45

# ssh: '{{2}} -o LogLevel=QUIET -p {{global.sshport}}'

longname:
  watch: true
  verbose: 1
  description:
    - writes a long sentence.
  ssh: -tt -o LogLevel=QUIET -p 45
  exec-locale:
    - echo 'hello world 11'
  # rsync:
  #   - exclude:
  #     - node_modules
  #     - .git
  #   - rsh: ssh -p 45
  #   - archive
  #   - recursive
  #   - verbose

    # - sudo rm -rf {{remotefold}}

  # verbose: 0

  # watch: false

# compile.all:
  # exec-finale:
#     - echo
    # - *pkg
    # - lsc -bco dist src
  # - lsc -bc test
    # - node {{global.file}}

    # - lsc -bco dist/{{global.proj}} src/{{global.proj}}
    # - lsc -bc test/{{global.proj}}
    # - node {{global.file}}

# exec-remote:
#   - echo 'hello world'
#   - rm -rf {{remotefold}}

# exec-locale:
#   - echo 'hello world 3'


#   - rsh: ssh
#   - verbose
#   - recursive
#   - exclude:
#     - .git
#     - node_modules

# version.update: update-version src/package.yaml remotemon


# bar:
#   defargs: [hello,world]
#   exec-locale:
#     - echo 'from command line {{0}}'