rsync:
  - src: "."
  - recursive
  - quiet
  - archive
ssh:
  option: -t -o LogLevel=QUIET
  startwith: []
service_directory: null
last_check_time: 0
histsize: 15
watch: ["."]
inpwd: false
ignore:
  - ".remotemon.yaml"
