name: remotemon
author: sourcevault
email: joykrishnamondal@gmail.com
homepage: https://github.com/sourcevault/remotemon#readme.md
license: BSD-3-Clause
description: remote monitoring, since there is no ansible for raspberry pi.
repository: https://github.com/sourcevault/remotemon.git
version: 2.1.8
main: dist/main.js
scripts:
  "test": "make travis"
bin:
  remotemon: dist/cmdline.js
dependencies:
  "@most/create": "*"
  option-parser: 1.0.1
  chokidar: 3.5.2
  hoplon: 1.0.3
  ramda: 0.27.1
  most: "*"
  yaml: 2.0.0-7
  boxen: 6.2.1
  emphasize: 5.0.0
  moment: 2.29.4
keywords:
  - remote
  - ssh
  - monitoring
  - raspberry-pi
  - rsync
  - chokidar
  - ansible
  - project
