name: remotemon
author: sourcevault
email: joykrishnamondal@gmail.com
homepage: https://github.com/sourcevault/remotemon#readme.md
license: MIT
description: remote monitoring
repository: https://github.com/sourcevault/remotemon.git
version: 0.0.1
main: dist/main.js
scripts:
  "test": "make travis"
dependencies:
  seamless-immutable: "7.1.4"
  ramda: "0.26.1"
  chalk: "2.4.2"
  json-stringify-pretty-compact: "2.0.0"
  guard-js: "0.1.1"
  seamless-immutable-mergers: "7.1.0"
  traverse: "0.6.6"
  at-line: "1.0.0"
  pretty-error: "2.1.1"
  js-yaml: "*"
  chokidar: "*"
  is-my-json-valid: "*"
  valleydate: "0.0.3"
  optionator: "*"
keywords:
  - "remote"
  - "ssh"
  - "monitoring"
  - "raspberry-pi"
  - "rsync"
  - "chokidar"


