name: remotemon
author: sourcevault
email: joykrishnamondal@gmail.com
homepage: https://github.com/sourcevault/remotemon#readme.md
license: BSD-3-Clause
description: remote monitoring, since there is no ansible for raspberry pi.
repository: https://github.com/sourcevault/remotemon.git
version: 1.3.6
main: dist/main.js
scripts:
  "test": "make travis"
bin:
  remotemon: dist/cmdline.js
dependencies:
  "@most/create": 2.0.1
  option-parser: 1.0.1
  chokidar: 3.5.2
  tampax: 1.2.2
  hoplon: 0.2.30
  ramda: 0.27.1
  most: 1.9.0
  yaml: 2.0.0-7
  boxen: 6.2.1
keywords:
  - remote
  - ssh
  - monitoring
  - raspberry-pi
  - rsync
  - chokidar
  - ansible
  - project
